apiVersion: spec.keptn.sh/0.2.2
kind: "Shipyard"
metadata:
  name: "woolworths-rollback-poc"
spec:
  stages:
    - name: "dev"
      sequences:
      - name: "delivery"
        tasks: 
        - name: "evaluation"
    - name: "pt"
      sequences:
      - name: "delivery"
        tasks: 
        - name: "evaluation"
    - name: "production"
      sequences:
      - name: "delivery"
        tasks: 
        - name: "evaluation"